version: "0.0.1"
services:
  db:
    container_name: taskitory-db
    image: postgres:14.1
    environment:
      - POSTGRES_DB=${DATENBANK_NAME}
      - POSTGRES_USER=${DATENBANK_ADMIN_USER}
      - POSTGRES_PASSWORD=${DATENBANK_ADMIN_PW}
      - PGDATA=/data/postgres
    volumes:
      - ./postgres-volume:/data
    networks:
      - taskitory-net
    ports:
      - "60000:5432"
    restart: unless-stopped
  iam:
    container_name: taskitory-iam
    image: jboss/keycloak:16.1.0
    networks:
      - taskitory-net
    environment:
      - DB_VENDOR=postgres
      - DB_USER=${DATENBANK_ADMIN_USER}
      - DB_PASSWORD=${DATENBANK_ADMIN_PW}
      - DB_ADDR=${DATENBANK_ADDR_ALIAS}
      - DB_PORT=${DATENBANK_PORT}
      - DB_DATABASE=${DATENBANK_NAME}
      - DB_SCHEMA=${DATENBANK_IAM_SCHEMA}
      - KEYCLOAK_USER=${IAM_ADMIN_USER}
      - KEYCLOAK_PASSWORD=${IAM_ADMIN_PW}
    ports:
      - "50004:8443"
    depends_on:
      - db
    restart: unless-stopped
  backend:
    container_name: taskitory-backend
    build: .
    networks:
      - taskitory-net
    ports:
      - "80:8080"
    depends_on:
      - db
      - iam
networks:
  taskitory-net:
    driver: bridge
